# Resolve react_native_pods.rb with node to allow for hoisting
require Pod::Executable.execute_command('node', ['-p',
  'require.resolve(
    "react-native/scripts/react_native_pods.rb",
    {paths: [process.argv[1]]},
  )', __dir__]).strip

platform :ios, min_ios_version_supported
prepare_react_native_project!

linkage = ENV['USE_FRAMEWORKS']
if linkage != nil
  Pod::UI.puts "Configuring Pod with #{linkage}ally linked Frameworks".green
  use_frameworks! :linkage => linkage.to_sym
end

target 'TSEClient' do
  config = use_native_modules!


  use_react_native!(
    :path => config[:reactNativePath],
    :hermes_enabled => true,   # or false if you aren't using Hermes
    :fabric_enabled => false,  # set true only if using the New Architecture
    :app_path => "#{Pod::Config.instance.installation_root}/.."
    # :ccache_enabled => true   # optional; comment or keep WITH a value
  )

  post_install do |installer|
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false,
      # :ccache_enabled => true
    )
  end
end
